"""Incident templates and root-cause signatures for the synthetic MVP."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class IncidentTemplate:
    key: str
    category: str
    root_cause: str
    severity: str
    alert_message: str
    topology_role: str
    impacted_service: str
    change_action: str
    change_device_role: str
    log_events: tuple[str, ...]
    metric_points: tuple[tuple[str, str, int, int, str], ...]
    signatures: tuple[str, ...]
    immediate_actions: tuple[str, ...]
    verification_actions: tuple[str, ...]
    long_term_prevention: tuple[str, ...]


TEMPLATES: tuple[IncidentTemplate, ...] = (
    IncidentTemplate(
        key="broadcast-loop",
        category="network",
        root_cause="Broadcast Loop",
        severity="critical",
        alert_message="Core switch CPU high and broadcast storm detected",
        topology_role="access_switch",
        impacted_service="campus_lan",
        change_action="Enable trunk port 1/1/48 without loop guard validation",
        change_device_role="access_switch",
        log_events=("stp_topology_change", "mac_flapping", "broadcast_storm", "arp_flood"),
        metric_points=(("switch", "cpu_usage", 96, 85, "%"), ("switch", "broadcast_pps", 190000, 50000, "pps")),
        signatures=("broadcast", "loop", "mac_flapping", "broadcast_storm", "stp_topology_change", "arp_flood"),
        immediate_actions=("Shut or isolate the suspected access port", "Verify STP state and loop guard on the access switch"),
        verification_actions=("Confirm MAC flapping stops", "Confirm broadcast packets per second returns below threshold"),
        long_term_prevention=("Enable loop guard/BPDU guard on edge ports", "Add pre-change validation for trunk enablement"),
    ),
    IncidentTemplate(
        key="stp-failure",
        category="network",
        root_cause="STP Failure",
        severity="critical",
        alert_message="STP instability detected on core network",
        topology_role="core_switch",
        impacted_service="campus_lan",
        change_action="Change STP priority on aggregation switch",
        change_device_role="core_switch",
        log_events=("root_bridge_change", "stp_blocking_missing", "bpdu_guard_disabled", "topology_recalculation"),
        metric_points=(("switch", "stp_change_count", 35, 5, "changes"), ("switch", "packet_loss", 24, 5, "%")),
        signatures=("stp", "root_bridge_change", "bpdu", "blocking", "topology_recalculation"),
        immediate_actions=("Restore known-good STP priority", "Re-enable BPDU guard where it was disabled"),
        verification_actions=("Confirm a stable root bridge", "Check that redundant links are blocking correctly"),
        long_term_prevention=("Document STP root design", "Add automated guardrail for STP priority changes"),
    ),
    IncidentTemplate(
        key="interface-flapping",
        category="network",
        root_cause="Interface Flapping",
        severity="major",
        alert_message="Repeated link up/down events on uplink interface",
        topology_role="access_switch",
        impacted_service="branch_connectivity",
        change_action="Replace patch cable on uplink Gi1/0/24",
        change_device_role="access_switch",
        log_events=("link_down", "link_up", "lacp_member_removed", "crc_errors"),
        metric_points=(("switch", "interface_flap_count", 18, 3, "flaps"), ("switch", "crc_error_rate", 2200, 100, "errors/min")),
        signatures=("flap", "link_down", "link_up", "crc_errors", "lacp_member_removed"),
        immediate_actions=("Move traffic to a stable uplink if available", "Inspect cable, optic, and switchport errors"),
        verification_actions=("Confirm flap count remains zero for 15 minutes", "Check CRC and input error counters"),
        long_term_prevention=("Replace suspect physical media", "Add alerting for repeated link state changes"),
    ),
    IncidentTemplate(
        key="camera-access-port-down",
        category="network",
        root_cause="Mistaken Camera Access Port Shutdown",
        severity="major",
        alert_message="Camera 01 unreachable from VMS/NVR",
        topology_role="access_switch",
        impacted_service="video_surveillance",
        change_action="Shutdown access port ge-0/0/1 during switch cleanup",
        change_device_role="access_switch",
        log_events=(
            "config_port_shutdown",
            "link_down",
            "poe_power_lost",
            "camera_heartbeat_lost",
            "rtsp_session_timeout",
        ),
        metric_points=(
            ("access_switch", "port_oper_status", 0, 1, "state"),
            ("access_switch", "poe_power_draw_w", 0, 4, "W"),
            ("access_switch", "crc_error_rate", 850, 100, "errors/min"),
        ),
        signatures=(
            "camera",
            "cam",
            "cctv",
            "nvr",
            "vms",
            "camera_down",
            "camera_unreachable",
            "access_port_down",
            "config_port_shutdown",
            "admin_down",
            "port_shutdown",
            "poe_power_lost",
            "camera_heartbeat_lost",
            "rtsp_session_timeout",
            "ge-0/0/1",
            "link_down",
        ),
        immediate_actions=(
            "Check switch port ge-0/0/1 admin/oper status and remove mistaken shutdown if confirmed",
            "Verify PoE power, cable/patch panel, and camera link light before replacing the device",
            "Review recent access-switch configuration changes around the outage window",
        ),
        verification_actions=(
            "Confirm camera ping and RTSP stream recover from VMS/NVR",
            "Confirm port ge-0/0/1 stays up and PoE draw is stable for 15 minutes",
            "Check VMS/NVR heartbeat status for Camera 01",
        ),
        long_term_prevention=(
            "Protect camera access ports with approved change templates",
            "Add monitoring for camera heartbeat plus switch port admin-down events",
            "Require peer review before bulk access-port cleanup changes",
        ),
    ),
    IncidentTemplate(
        key="routing-issue",
        category="network",
        root_cause="Routing Issue",
        severity="major",
        alert_message="Route withdrawal causing reachability loss",
        topology_role="edge_router",
        impacted_service="wan",
        change_action="Update BGP prefix filter",
        change_device_role="edge_router",
        log_events=("bgp_neighbor_reset", "route_withdrawal", "prefix_denied", "next_hop_unreachable"),
        metric_points=(("router", "route_count", 120, 400, "routes"), ("router", "packet_loss", 32, 5, "%")),
        signatures=("routing", "bgp", "route_withdrawal", "prefix_denied", "next_hop_unreachable"),
        immediate_actions=("Rollback the prefix filter if it matches the outage window", "Verify BGP neighbor state"),
        verification_actions=("Confirm expected prefixes are installed", "Run reachability tests from affected segments"),
        long_term_prevention=("Peer-review route policy changes", "Add route-count anomaly alerts"),
    ),
    IncidentTemplate(
        key="firewall-session-exhaustion",
        category="network",
        root_cause="Firewall Session Exhaustion",
        severity="critical",
        alert_message="Firewall session table near capacity",
        topology_role="firewall",
        impacted_service="internet_edge",
        change_action="Enable new outbound NAT policy",
        change_device_role="firewall",
        log_events=("session_spike", "session_table_full", "syn_flood_pattern", "new_nat_policy_hit"),
        metric_points=(("firewall", "session_utilization", 98, 85, "%"), ("firewall", "cpu_usage", 93, 85, "%")),
        signatures=("firewall", "session", "session_table_full", "session_spike", "nat", "syn_flood"),
        immediate_actions=("Identify top session sources and destinations", "Apply temporary rate limit for abusive flows"),
        verification_actions=("Confirm session utilization drops below 75%", "Check legitimate traffic success rate"),
        long_term_prevention=("Capacity-plan session table usage", "Add per-policy session monitoring"),
    ),
    IncidentTemplate(
        key="dns-failure",
        category="network",
        root_cause="DNS Failure",
        severity="major",
        alert_message="DNS resolution failures reported by multiple services",
        topology_role="dns_server",
        impacted_service="name_resolution",
        change_action="Update DNS forwarder configuration",
        change_device_role="dns_server",
        log_events=("dns_timeout", "servfail_spike", "forwarder_unreachable", "cache_miss_spike"),
        metric_points=(("dns", "dns_error_rate", 72, 10, "%"), ("dns", "query_latency_ms", 4300, 500, "ms")),
        signatures=("dns", "servfail", "forwarder", "dns_timeout", "cache_miss"),
        immediate_actions=("Restore previous DNS forwarder configuration", "Fail over clients to secondary DNS"),
        verification_actions=("Resolve representative internal and external records", "Check DNS latency and SERVFAIL rate"),
        long_term_prevention=("Health-check DNS forwarders before changes", "Add synthetic DNS resolution probes"),
    ),
    IncidentTemplate(
        key="internet-congestion",
        category="network",
        root_cause="Internet Congestion",
        severity="major",
        alert_message="Internet edge latency and packet loss elevated",
        topology_role="internet_edge",
        impacted_service="external_connectivity",
        change_action="Start backup replication job across internet link",
        change_device_role="internet_edge",
        log_events=("wan_latency_spike", "packet_drop", "bandwidth_saturation", "qos_queue_full"),
        metric_points=(("wan", "bandwidth_utilization", 99, 85, "%"), ("wan", "latency_ms", 780, 150, "ms")),
        signatures=("internet", "congestion", "bandwidth_saturation", "qos_queue_full", "latency"),
        immediate_actions=("Throttle or pause the high-volume job", "Prioritize business-critical traffic"),
        verification_actions=("Confirm bandwidth utilization and latency normalize", "Run external path tests"),
        long_term_prevention=("Schedule large transfers outside peak hours", "Tune QoS policies for backup traffic"),
    ),
    IncidentTemplate(
        key="disk-full",
        category="system",
        root_cause="Disk Full",
        severity="critical",
        alert_message="Application host disk usage critical",
        topology_role="app_server",
        impacted_service="application",
        change_action="Enable verbose application logging",
        change_device_role="app_server",
        log_events=("disk_space_low", "log_growth_spike", "write_failed_no_space", "service_degraded"),
        metric_points=(("server", "disk_usage", 99, 85, "%"), ("server", "log_dir_growth_gb", 42, 10, "GB")),
        signatures=("disk", "no_space", "disk_space_low", "log_growth", "write_failed"),
        immediate_actions=("Rotate or archive non-essential logs", "Free space on the affected volume"),
        verification_actions=("Confirm disk usage drops below threshold", "Verify application writes succeed"),
        long_term_prevention=("Set log retention limits", "Add disk growth forecasting alerts"),
    ),
    IncidentTemplate(
        key="cpu-exhaustion",
        category="system",
        root_cause="CPU Exhaustion",
        severity="major",
        alert_message="Server CPU sustained above threshold",
        topology_role="app_server",
        impacted_service="application",
        change_action="Deploy compute-heavy report job",
        change_device_role="app_server",
        log_events=("worker_queue_backlog", "high_load_average", "slow_request", "cpu_saturation"),
        metric_points=(("server", "cpu_usage", 98, 85, "%"), ("server", "load_average", 32, 8, "load")),
        signatures=("cpu", "load", "cpu_saturation", "worker_queue_backlog", "slow_request"),
        immediate_actions=("Stop or throttle the offending job", "Scale out workers if capacity is available"),
        verification_actions=("Confirm CPU and load average normalize", "Check request latency after mitigation"),
        long_term_prevention=("Add job resource limits", "Profile expensive workloads before release"),
    ),
    IncidentTemplate(
        key="memory-leak",
        category="system",
        root_cause="Memory Leak",
        severity="critical",
        alert_message="Memory usage increasing until process restart",
        topology_role="app_server",
        impacted_service="application",
        change_action="Deploy new application version",
        change_device_role="app_server",
        log_events=("heap_growth", "oom_kill", "gc_pressure", "process_restart"),
        metric_points=(("server", "memory_usage", 97, 85, "%"), ("server", "swap_usage", 81, 40, "%")),
        signatures=("memory", "heap", "oom", "gc_pressure", "swap", "process_restart"),
        immediate_actions=("Restart the leaking service if impact is active", "Rollback the version if leak started after deploy"),
        verification_actions=("Track memory slope after restart or rollback", "Check for repeated OOM events"),
        long_term_prevention=("Add memory regression tests", "Instrument heap usage by endpoint/job"),
    ),
    IncidentTemplate(
        key="service-crash",
        category="system",
        root_cause="Service Crash",
        severity="critical",
        alert_message="Critical service stopped unexpectedly",
        topology_role="app_server",
        impacted_service="application",
        change_action="Deploy new dependency version",
        change_device_role="app_server",
        log_events=("uncaught_exception", "service_exit", "restart_loop", "dependency_error"),
        metric_points=(("server", "service_availability", 0, 1, "state"), ("server", "restart_count", 12, 2, "restarts")),
        signatures=("service", "crash", "uncaught_exception", "service_exit", "restart_loop", "dependency_error"),
        immediate_actions=("Rollback the dependency or deployment", "Start the service in safe mode if available"),
        verification_actions=("Confirm service stays running", "Exercise the failing endpoint or workflow"),
        long_term_prevention=("Pin dependencies and add smoke tests", "Improve exception handling around startup"),
    ),
    IncidentTemplate(
        key="vmware-datastore-full",
        category="system",
        root_cause="VMware Datastore Full",
        severity="critical",
        alert_message="VMware datastore capacity exhausted",
        topology_role="vmware_datastore",
        impacted_service="virtualization",
        change_action="Create large VM snapshot",
        change_device_role="vmware_datastore",
        log_events=("datastore_low_space", "snapshot_growth", "vm_stun", "thin_provisioning_alarm"),
        metric_points=(("vmware", "datastore_usage", 99, 85, "%"), ("vmware", "snapshot_size_gb", 650, 100, "GB")),
        signatures=("vmware", "datastore", "snapshot", "vm_stun", "thin_provisioning"),
        immediate_actions=("Remove or consolidate unneeded snapshots", "Migrate VMs or extend datastore capacity"),
        verification_actions=("Confirm datastore free space recovers", "Check affected VM IO latency"),
        long_term_prevention=("Enforce snapshot age and size policy", "Alert on fast datastore growth"),
    ),
    IncidentTemplate(
        key="vmware-host-failure",
        category="system",
        root_cause="VMware Host Failure",
        severity="critical",
        alert_message="VMware host unavailable and VMs restarted elsewhere",
        topology_role="vmware_host",
        impacted_service="virtualization",
        change_action="Firmware maintenance completed on ESXi host",
        change_device_role="vmware_host",
        log_events=("host_not_responding", "ha_vm_restart", "storage_path_lost", "management_agent_down"),
        metric_points=(("vmware", "host_heartbeat_loss", 1, 0, "state"), ("vmware", "vm_restart_count", 17, 1, "restarts")),
        signatures=("vmware", "host", "ha_vm_restart", "host_not_responding", "heartbeat", "storage_path_lost"),
        immediate_actions=("Keep affected host out of service", "Verify cluster HA capacity and VM placement"),
        verification_actions=("Confirm host management and storage paths are stable", "Check restarted VM health"),
        long_term_prevention=("Add post-maintenance host validation", "Review firmware and driver compatibility"),
    ),
    IncidentTemplate(
        key="brute-force-attack",
        category="security",
        root_cause="Brute Force Attack",
        severity="critical",
        alert_message="Authentication failures exceed security threshold",
        topology_role="identity_server",
        impacted_service="identity",
        change_action="Expose VPN portal to new partner IP range",
        change_device_role="firewall",
        log_events=("failed_login_spike", "account_lockout", "same_source_many_users", "vpn_auth_failure"),
        metric_points=(("security", "failed_login_rate", 2400, 200, "events/min"), ("security", "lockout_count", 80, 10, "accounts")),
        signatures=("brute", "failed_login", "account_lockout", "same_source", "vpn_auth"),
        immediate_actions=("Block or rate-limit abusive source IPs", "Protect targeted accounts with MFA checks"),
        verification_actions=("Confirm failed-login rate returns to baseline", "Review successful logins during the window"),
        long_term_prevention=("Add adaptive lockout and geo-risk controls", "Tune VPN authentication monitoring"),
    ),
    IncidentTemplate(
        key="malware-activity",
        category="security",
        root_cause="Malware Activity",
        severity="critical",
        alert_message="Endpoint malware behavior detected",
        topology_role="endpoint",
        impacted_service="endpoint_security",
        change_action="User opened suspicious attachment",
        change_device_role="endpoint",
        log_events=("suspicious_process", "c2_beacon", "file_encryption_activity", "edr_detection"),
        metric_points=(("security", "malware_alert_count", 7, 1, "alerts"), ("endpoint", "process_spawn_rate", 190, 50, "proc/min")),
        signatures=("malware", "c2", "beacon", "suspicious_process", "file_encryption", "edr"),
        immediate_actions=("Isolate the endpoint from the network", "Collect volatile evidence before remediation"),
        verification_actions=("Confirm no further C2 beaconing", "Scan adjacent endpoints for the same indicators"),
        long_term_prevention=("Improve attachment sandboxing", "Add EDR detections for observed indicators"),
    ),
    IncidentTemplate(
        key="port-scanning",
        category="security",
        root_cause="Port Scanning",
        severity="major",
        alert_message="Port scanning activity detected against server subnet",
        topology_role="server_subnet",
        impacted_service="security_monitoring",
        change_action="Temporary firewall allow rule added for assessment",
        change_device_role="firewall",
        log_events=("many_destination_ports", "syn_scan", "horizontal_scan", "ids_scan_alert"),
        metric_points=(("security", "unique_port_count", 1200, 100, "ports"), ("security", "connection_attempt_rate", 9000, 500, "conn/min")),
        signatures=("port", "scan", "syn_scan", "horizontal_scan", "many_destination_ports", "ids_scan"),
        immediate_actions=("Confirm whether the scanner is authorized", "Block the source if unauthorized"),
        verification_actions=("Check IDS alerts stop after mitigation", "Validate no exploit attempts followed the scan"),
        long_term_prevention=("Maintain approved scanner allowlist", "Add detection for scanning followed by authentication attempts"),
    ),
    IncidentTemplate(
        key="lateral-movement",
        category="security",
        root_cause="Lateral Movement",
        severity="critical",
        alert_message="Suspicious east-west authentication and remote execution",
        topology_role="server_subnet",
        impacted_service="internal_security",
        change_action="Admin credential used from unusual workstation",
        change_device_role="identity_server",
        log_events=("remote_exec", "admin_share_access", "unusual_logon_path", "credential_reuse"),
        metric_points=(("security", "lateral_auth_count", 140, 20, "auths"), ("security", "remote_exec_count", 19, 1, "execs")),
        signatures=("lateral", "remote_exec", "admin_share", "credential_reuse", "unusual_logon"),
        immediate_actions=("Disable or reset suspected credentials", "Isolate hosts in the suspicious path"),
        verification_actions=("Confirm no new remote execution events", "Review privileged logons during the incident window"),
        long_term_prevention=("Implement privileged access segmentation", "Add detections for unusual admin graph paths"),
    ),
)


TEMPLATES_BY_KEY = {template.key: template for template in TEMPLATES}
TEMPLATES_BY_ROOT_CAUSE = {template.root_cause: template for template in TEMPLATES}
CATEGORIES = tuple(sorted({template.category for template in TEMPLATES}))
